
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/03_minibatch_training_jcat.ipynb

from exp.nb_02 import *
import torch.nn.functional as F

# accuracy is the fraction of correct predictions
# predicted class is torch.argmax(prediction_probs, dim=1)==target)
def accuracy(prediction_probs, target):
    return (torch.argmax(prediction_probs, dim=1)==target).float().mean()

from torch import optim

# returns a tuple of data and labels
class Dataset():
    def __init__(self, x, y): self.x,self.y = x,y
    def __len__(self): return len(self.x)
    def __getitem__(self, i): return self.x[i],self.y[i]

from torch.utils.data import DataLoader, SequentialSampler, RandomSampler

# note double batch size for validation data set, since it needs less storage because it has no gradients
def get_dls(train_ds, valid_ds, bs, **kwargs):
    return (DataLoader(train_ds, batch_size=bs, shuffle=True, **kwargs),
            DataLoader(valid_ds, batch_size=bs*2, **kwargs))